[build] on win32 - linking is broken since r21669 : src\utils.o: In function `Parrot_byte_index':C:/fperrad/Parrot/trunk/src/utils.c:660: undefined reference to `index' - replace index() by strchr() which is C89
git-svn-id: https://svn.parrot.org/parrot/trunk@21715 d31e2699-5ff4-0310-a27c-f18f2fbe73fe