Two small building problems (r8030)
1) On MinGW, can't execute miniparrot.exe during building
Invoking Parrot to generate runtime/parrot/include/config.fpmc --cross your
fingers
./miniparrot.exe config_lib.pasm > runtime/parrot/include/config.fpmc
'.' is not recognized as an internal or external command, operable program
or batch file.

2) 'make hello' fails on linking, because src/parrot_config.o is missing
blib/lib/libparrot.a(global_setup.o)(.text+0x240): In function
`create_config_hash':
trunk/src/global_setup.c:33: undefined reference to `parrot_get_config_string'

Nota : the target exec_so seems to have the same problem

Courtesy of François Perrad <francois.perrad@gadz.org>


git-svn-id: https://svn.parrot.org/parrot/trunk@8041 d31e2699-5ff4-0310-a27c-f18f2fbe73fe